Listar ongs
yagoal/connect-ong pull request #35
Opened 2022-10-04 23:06 UTC by ValLins18

## 🌀 Descrição
Este PR implementa a segregação dos animais a partir de suas respectivas ONGS, o intuito é que a aplicação leve para o usuario uma maior organização e liberdade na escolha dos animais, tendo em vista que ele tambem poderá escolher de qual ONG o animal virá.

## 🔬 Como testar

1. Logar um usuario `docType = 'cpf'`
2. Em `MeuPerfil.jsp` clicar em adotar e você será redirecionado para `OngsDisponiveis.jsp`.
3. Escolha uma Ong e logo em seguida clique em +informações e você será redirecionado para `AnimaisDisponiveis.jsp`.
4. Em `AnimaisDisponiveis.jsp` escolha um animal para adotar e confira se as informações de quantidade de adoções do usuario e quantidade de animais das Ongs foram atualizadas.

2022-10-05 06:31 UTC, marianemxr commented
**1. Logar um usuário docType = 'cpf':** OK. Tudo certo no procedimento de login;

**2. Em MeuPerfil.jsp clicar em adotar e você será redirecionado para OngsDisponiveis.jsp:** OK. O redirecionamento ocorreu conforme o esperado. Apenas será necessário alterar o título da página (no head do html) para "ONGs Disponíveis", pois o nome está "Animais Disponíveis";

**3. Escolha uma Ong e logo em seguida clique em +informações e você será redirecionado para AnimaisDisponiveis.jsp:** OK. O redirecionamento ocorreu conforme o esperado. Ao clicar na ONG fundada em 2022, nenhum animal é listado, pois realmente não há nenhum animal cadastrado na ONG em questão. Ao clicar na ONG fundada em 1998, são listados dois animais (Pituca e Jupiter), ou seja, também está correto. 

**4. Em AnimaisDisponiveis.jsp escolha um animal para adotar e confira se as informações de quantidade de adoções do usuário e quantidade de animais das Ongs foram atualizadas:** Escolhi adotar a Pituca. Ao adotar, tudo ok. No texto da página de finalização da adoção, será necessário coletar o nome do animal adotado para que seja exibido no texto, pois o nome está Lilica em todas as adoções, conforme pode ser verificado na imagem abaixo:

![image](https://user-images.githubusercontent.com/95103063/193993967-83bbde4a-3e88-49f7-8149-83b627f0bbc9.png)

Notei um problema em relação a essa adoção em específico. A Pituca aparece duas vezes para mim na página "Minhas Adoções":

![image](https://user-images.githubusercontent.com/95103063/193994154-a18194fd-b046-400a-a0a9-135517387d42.png)

Chequei o banco de dados para saber se, por coincidência, a gente tinha cadastrado dois animais com o mesmo nome e se eu tinha adotado os dois, porém realmente a adoção foi computada erroneamente em dobro. Percebam que o ID do animal é o mesmo e a adoção de ID 66 foi cadastrada 4 segundos após a 65:

![image](https://user-images.githubusercontent.com/95103063/193994473-2ff14ee4-4e13-4d2d-805a-3440b46c51d5.png)

Depois, para entender o que tava acontecendo, resolvi adotar o Jupiter e ocorreu tudo normal... então não sei bem qual foi o problema. 

![image](https://user-images.githubusercontent.com/95103063/193995399-ed6b5595-a227-436e-8fe0-4bc20e00e3d0.png)

Por ora, está tudo ok então... vou cadastrar mais animais para que Yago possa realizar o teste também e verificar se o erro que mencionei só aconteceu comigo. E sobre as pequenas alterações que citei nos tópicos 2 (sobre o título da página) e 4 (sobre o nome do animal), já irei resolvê-las.

2022-10-05 07:09 UTC, marianemxr commented
Val, eu tentei cadastrar mais animais, mas não consegui... ou melhor, consegui mas não do jeito que eu gostaria, porque os animais (Amy e Terry) foram cadastrados no banco de dados, mas não consigo visualizá-los pertencendo a uma ONG, ou seja, eles não aparecem na minha página de "Animais Disponíveis". Mais tarde, verei isso com mais calma.

2022-10-05 11:23 UTC, yagoal requested changes

2022-10-05 11:23 UTC, yagoal commented on src/main/java/controller/OngAnimalsController.java
> +		System.out.println(request.getParameter("id"));
Da pra remover esse print aqui

2022-10-05 11:25 UTC, yagoal commented
aparetemente tudo funcionando, mas já não seria o caso add a lógica de cadastro dos animais dentro de um user ong e já acrescentar a sua respetiva lista, sem necessariamente setar diretamente no banco de dados ?

@marianemxr tá assim porque a adoção é só um true e false, e quando setamos direto no banco o animal passa a estar disponível novamente, ai adotando fica repetido mesmo, mas quando limparmos o banco isso vai resolver

2022-10-05 11:28 UTC, yagoal requested changes

2022-10-05 11:28 UTC, yagoal commented on src/main/java/controller/OngsDisponiveisController.java
> +public class OngsDisponiveisController extends HttpServlet {
Mesmo logado no header clicando em AnimaisDisponíveis da um nullpointer excecption, acho que falta ajustar algo nesse redirect, não consegui identificar direito

2022-10-05 11:40 UTC, marianemxr commented on src/main/java/controller/OngsDisponiveisController.java
> +public class OngsDisponiveisController extends HttpServlet {
Sim, tem razão. Aqui também percebi esse problema.

2022-10-05 11:41 UTC, marianemxr commented
Entendi, @yagoal. Obrigada pela explicação!!

2022-10-10 21:27 UTC, yagoal approved these changes

2022-10-11 11:22 UTC, merged