Feat editar perfil de usuario CPF
yagoal/connect-ong pull request #37
Opened 2022-10-15 01:26 UTC by ValLins18

## 🌀 Descrição
Este PR implementa a logica de atualização de cadastro de usuarios do tipo CPF atraves da tela de perfil.

## 🔬 Como testar

1. Abrir a tela `Cadastro.jsp`.
2. Como não tem nenhuma sessão iniciada a tela de cadastro virá completa.
3. Preencha o formulario e cadastre seu usuario.
4. Faça o Login do usuario que acabou de cadastrar e em `MeuPerfil.jsp` clique no dropdown button logo abaixo e verá a nova opção de `Alterar perfil` e você será redirecionado para `Cadastro.jsp` só que de uma forma reestruturada, pois não será permitido alterar informações sensiveis, como e-mail e senha (por enquanto...).
5. ![image](https://user-images.githubusercontent.com/94613489/195962736-40835f50-e51c-452a-8f11-2c9a893934a8.png)
6. Preencha o que quiser alterar (Alterar a foto de perfil é um bom teste!).
7. Você será redirecionado para `SucessoAlteracao.jsp`.
8. clique no botão de login para que seja feito o logout e faça o login novamente para que suas informações sejam atualizadas com base na sessão.

2022-10-15 07:53 UTC, marianemxr commented
**1. Abrir a tela `Cadastro.jsp`:** OK. 

> Apenas uma observação: seria interessante diminuir o tamanho da imagem de "no photo" para que ela fique no centro da página, adequando-se ao botão de "Escolher Arquivo":

![image](https://user-images.githubusercontent.com/95103063/195973868-068760b5-9c48-437f-a4c0-cd91d383b232.png)

> **- OBS: O tamanho da pré-visualização da imagem de perfil já tá ótimo:** 

![image](https://user-images.githubusercontent.com/95103063/195973957-b967583b-42c9-45ef-8fa6-1ac50ae84995.png)

**2. Como não tem nenhuma sessão iniciada, a tela de cadastro virá completa:** OK. 
**3. Preencha o formulário e cadastre seu usuário:** 

> O cadastro foi realizado, porém `as validações não foram executadas corretamente`, pois coloquei os mesmos CPF e e-mail cadastrados em minha outra conta, apenas pra testar se tudo estava funcionando corretamente, e a tela de sucesso de cadastro apareceu para mim, como se eu tivesse conseguido cadastrar a conta nova. Verifiquei o console do Eclipse e o seguinte erro foi exibido: 

`Erro ao inserir User no banco: org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update`

> Além disso, verifiquei o banco de dados e o novo usuário realmente não foi cadastrado. 

> Porém, para o usuário, a sensação é de que realmente foi criada uma nova conta utilizando os mesmos CPF e e-mail cadastrados anteriormente. 

> Após realizar o teste citado, criei uma conta nova utilizando `CPF e e-mail diferentes dos anteriores`.

**4. Faça o Login do usuário que acabou de cadastrar e, em `MeuPerfil.jsp`, clique no dropdown button, logo abaixo, e verá a nova opção de `Alterar perfil`. Você será redirecionado para `Cadastro.jsp`, só que de uma forma reestruturada, pois não será permitido alterar informações sensíveis, como e-mail e senha (por enquanto...):** OK. 

> Os campos `e-mail` e `senha `não foram exibidos, conforme o esperado. 

> Apenas os campos `sexo`, `data de nascimento` e `estado` não estão preenchidos. 

> Conforme explicado no tópico 1, o tamanho da imagem (pré-visualizada) novamente estava inadequado, assim como o de "no photo", no tópico citado. Abaixo, vocês podem ver como ficou a visualização da minha foto de perfil na página de `alteração de dados do perfil`. O tamanho apenas ficou correto quando escolhi uma nova foto de perfil. Na página de perfil do usuário, o tamanho estava correto também. 

![image](https://user-images.githubusercontent.com/95103063/195975841-5d175b61-dd29-4fef-9310-0870823fa3f1.png)


**5. Preencha o que quiser alterar (Alterar a foto de perfil é um bom teste!):** OK.

> Tentei alterar apenas o CPF e não consegui, pois o botão de `Finalizar Cadastro` estava inativo. Após isso, troquei minha foto de perfil e o botão ficou ativo. Ou seja, o usuário apenas consegue realizar as alterações se também mudar a foto de perfil. Precisamos alterar isso, porque há situações em que o usuário apenas vai querer alterar a data de nascimento, por exemplo, e estará impossibilitado.

**6. Você será redirecionado para `SucessoAlteracao.jsp`:** OK.
**7. Clique no botão de login para que seja feito o logout e faça o login novamente para que suas informações sejam atualizadas com base na sessão.** OK. 

> As alterações foram atualizadas corretamente.

2022-10-15 08:01 UTC, marianemxr commented
### Considerações finais:

Os dados solicitados foram alterados na tela de edição de perfil e foram corretamente atualizados na página de `Meu Perfil`, porém é necessário realizar as seguintes alterações:
-  validações de CPF e e-mail existentes/já cadastrados;
- alterar o tamanho da imagem de `no photo` (na tela de `Cadastro`) e da imagem do usuário (na tela de `edição de perfil`). **OBS:** A tela de edição de perfil e a de Cadastro é a mesma, sendo assim, basta realizar as alterações na tela de `Cadastro` e ambos os problemas serão resolvidos;
- Deixar o usuário alterar qualquer informação de seu perfil, sem obrigá-lo a alterar a foto de perfil.

2022-10-15 08:21 UTC, marianemxr commented
Já alterei o tamanho da imagem de `no photo` (na tela de `Cadastro`) e da imagem do usuário (na tela de `edição de perfil`).

2022-10-15 16:39 UTC, yagoal requested changes

2022-10-15 16:39 UTC, yagoal commented on src/main/webapp/Cadastro.jsp
>      <main>
Algumas observações aqui:

Os campos CPF, sexo e data de nascimento não deveriam aparecer pra edição, pois são informações consideradas sensíveis também.

Você só consegue avançar o cadastro se trocar a foto, ou seja é mandatório mudar a foto e não deveria ser para questões de edição, está seguindo a regra do cadastro normal

O campo de Sigla de estado está vindo vazio, acho que deve faltar setar alguma regra pra ele já vir preenchido, pois seria bem chato pro usuário preencher qualquer que seja as coisas de novo.

2022-10-15 16:39 UTC, yagoal commented on src/main/webapp/Cadastro.jsp
> +                  </div>
Na linha 155 o botão continua com o nome de finalizar cadastro quando está editando, o correto seria o mudar o nome do botão para finalizar edição, e no caso de edição com todos os campos preenchidos o mesmo deveria já vir enabled, está disabled pelo motivo de alguns campos não estarem sendo preenchidos corretamente e a exigência da validação da foto, que deve ser descartada.

2022-10-15 16:41 UTC, yagoal commented
Outra observação é que acho que não deveria deslogar o usuário nesse caso de edição, pois deveria só ser mudadas infomações não essenciais, o logout só deve acontecer quando forem alteradas informações que são credenciais de acesso como e-mail e senha por exemplo, então acho que deveríamos manter o usuário logado e guardar as infomações atualizadas na sessão o que também seria bom para economizar requisições no banco de dados.

2022-10-31 00:37 UTC, yagoal approved these changes

2022-10-31 00:37 UTC, merged